# Generated by Django 2.2.6 on 2023-02-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
